using System.Text;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using KSR.AST;
using KSR.Lexer;
using KSR.Parser;

namespace KSR.Build;

/// <summary>
/// MSBuild task that compiles all .ksr source files into a single merged C# file.
///
/// Inputs:
///   KsrCompile   — the .ksr source items (set via KSR.Build.props glob)
///   OutputFile   — path to the generated .g.cs file (inside obj/)
///
/// The generated file is added to the Compile item group by KSR.Build.targets
/// so that Roslyn picks it up automatically.
/// </summary>
public class KsrCompileTask : Microsoft.Build.Utilities.Task
{
    // ── MSBuild task parameters ────────────────────────────────────────────────

    [Required]
    public ITaskItem[] KsrCompile { get; set; } = [];

    [Required]
    public string OutputFile { get; set; } = "";

    // ── ITask.Execute ─────────────────────────────────────────────────────────

    public override bool Execute()
    {
        Log.LogMessage(MessageImportance.Normal,
            $"KSR: compiling {KsrCompile.Length} source file(s) → {OutputFile}");

        // ── 1. Lex + Parse each source file ───────────────────────────────────

        var allDeclarations = new List<AstNode>();
        var hasErrors = false;

        foreach (var item in KsrCompile)
        {
            var path = item.GetMetadata("FullPath");
            string source;
            try
            {
                source = File.ReadAllText(path);
            }
            catch (Exception ex)
            {
                Log.LogError(null, null, null, path, 0, 0, 0, 0,
                    $"Cannot read file: {ex.Message}");
                hasErrors = true;
                continue;
            }

            List<Token> tokens;
            try
            {
                var lexer = new Lexer.Lexer(source);
                tokens = lexer.Tokenize();
            }
            catch (KsrLexException lex)
            {
                Log.LogError(null, null, null, path,
                    lex.Line, lex.Col, lex.Line, lex.Col,
                    lex.Message);
                hasErrors = true;
                continue;
            }
            catch (Exception ex)
            {
                Log.LogError(null, null, null, path, 1, 1, 1, 1,
                    $"Lexer error: {ex.Message}");
                hasErrors = true;
                continue;
            }

            ProgramNode ast;
            try
            {
                var parser = new KSR.Parser.Parser(tokens, path);
                ast = parser.Parse();
            }
            catch (KsrParseException pex)
            {
                Log.LogError(null, null, null, path,
                    pex.Line, pex.Col, pex.Line, pex.Col,
                    pex.Message);
                hasErrors = true;
                continue;
            }
            catch (Exception ex)
            {
                Log.LogError(null, null, null, path, 1, 1, 1, 1,
                    $"Parse error: {ex.Message}");
                hasErrors = true;
                continue;
            }

            allDeclarations.AddRange(ast.Declarations);
        }

        if (hasErrors)
            return false;

        // ── 2. Merge into one ProgramNode and generate C# ─────────────────────

        var merged = new ProgramNode(allDeclarations);
        string csharp;
        try
        {
            var gen = new CodeGen.CodeGenerator();
            csharp = gen.Generate(merged);
        }
        catch (Exception ex)
        {
            Log.LogError($"KSR code generator error: {ex.Message}");
            return false;
        }

        // ── 3. Write output only if changed (avoid unnecessary Roslyn rebuilds) ─

        try
        {
            var dir = Path.GetDirectoryName(OutputFile);
            if (!string.IsNullOrEmpty(dir))
                Directory.CreateDirectory(dir);

            // Prepend a header so the file is clearly machine-generated
            var header = new StringBuilder();
            header.AppendLine("// <auto-generated>");
            header.AppendLine("//   Generated by KSR compiler — do not edit.");
            header.AppendLine("// </auto-generated>");
            header.AppendLine();
            var final = header + csharp;

            if (!File.Exists(OutputFile) || File.ReadAllText(OutputFile) != final)
            {
                File.WriteAllText(OutputFile, final, Encoding.UTF8);
                Log.LogMessage(MessageImportance.Normal, $"KSR: wrote {OutputFile}");
            }
            else
            {
                Log.LogMessage(MessageImportance.Low, $"KSR: {OutputFile} unchanged, skipped.");
            }
        }
        catch (Exception ex)
        {
            Log.LogError($"KSR: cannot write output file '{OutputFile}': {ex.Message}");
            return false;
        }

        return true;
    }
}
